### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Xett**
Not sure if you're using 2.7 or not but I'm using some version of 3, brackets makes it work so I fixed a few to check it out.

I also added a .gitignore to ignore cached python files from being added to commits.

### CODE REVIEW

**Comment by Xett** [comment]
WASD input movement for the player was a series of successive if statements for each key. 2 of the keys would have overriden the other if both pressed? Not sure, didn't test that but it seemed like it would so I made it use 2 floats instead. 2 Floats leaves room for acceleration/deceleration in player movement.

**Comment by Xett** [comment]
Just noticed you actually have some velocity kinda clamping stuff in your player class, but this should just work with that.

**Comment by Xett** [comment]
I moved your individual components of the MVC framework into their own modules. You can use os and sys to add the relative top level path to import from the other modules, as in control.py.

**Review by ascedmor — APPROVED** [review]

**Review by ascedmor — APPROVED** [review]

**Review by ascedmor — APPROVED** [review]

**Review by ascedmor — APPROVED** [review]

**Review by ascedmor — APPROVED** [review]
This is really helpful, there are way too many if chains at the moment

**Pull request merged**
